
import React, { useState } from 'react';
import { getQuoteEstimate, QuoteEstimate } from '../services/geminiService';

const AIQuoteEstimator: React.FC = () => {
  const [description, setDescription] = useState('');
  const [estimate, setEstimate] = useState<QuoteEstimate | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleEstimate = async () => {
    if (!description.trim()) {
      setError('Please provide a project description.');
      return;
    }
    setIsLoading(true);
    setError(null);
    setEstimate(null);
    try {
      const result = await getQuoteEstimate(description);
      setEstimate(result);
    } catch (err: any) {
      setError(err.message || 'An unexpected error occurred.');
    } finally {
      setIsLoading(false);
    }
  };

  const formatCurrency = (amount: number, currency: string) => {
    return new Intl.NumberFormat('en-ZA', { style: 'currency', currency: currency }).format(amount);
  };

  return (
    <section className="py-16 md:py-24 bg-gradient-to-r from-primary to-secondary text-white">
      <div className="container mx-auto px-6">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold">AI-Powered Quote Estimator</h2>
          <p className="text-lg text-gray-200 mt-4 max-w-2xl mx-auto">Get an instant, AI-generated feasibility estimate for your project. Powered by Gemini.</p>
        </div>
        
        <div className="max-w-3xl mx-auto bg-white/10 backdrop-blur-sm p-8 rounded-lg shadow-2xl">
          <div className="flex flex-col gap-4">
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Describe your project here. For example: 'I need a small-scale water filtration system for a remote community, processing 5000 liters per hour...'"
              className="w-full h-32 p-4 rounded-md bg-white/20 text-white placeholder-gray-300 focus:ring-2 focus:ring-accent focus:outline-none transition"
              disabled={isLoading}
            />
            <button
              onClick={handleEstimate}
              disabled={isLoading}
              className="w-full bg-accent hover:bg-orange-600 text-white font-bold text-lg py-3 px-8 rounded-lg shadow-lg transform hover:scale-105 transition-all duration-300 disabled:bg-gray-500 disabled:cursor-not-allowed disabled:scale-100"
            >
              {isLoading ? 'Estimating...' : 'Get My Estimate'}
            </button>
          </div>

          {error && <div className="mt-4 p-4 bg-red-500/50 text-white rounded-md text-center">{error}</div>}

          {estimate && (
            <div className="mt-8 p-6 bg-white/20 rounded-lg animate-fade-in text-center">
              <h3 className="text-xl font-semibold mb-2">Your Estimated Project Range:</h3>
              <p className="text-3xl md:text-4xl font-bold text-accent mb-4">
                {formatCurrency(estimate.minEstimate, estimate.currency)} - {formatCurrency(estimate.maxEstimate, estimate.currency)}
              </p>
              <p className="text-gray-200">{estimate.summary}</p>
              <p className="text-sm mt-4 text-gray-300 italic">*This is a preliminary, non-binding estimate generated by AI.</p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
};

export default AIQuoteEstimator;
